### ISSUE TITLE
Support for franco's Gamma Control

### ISSUE THREAD

**Issue by spezi77** [yoinx/kernel_adiutor#1]
It would be great to use your app with kernels that come with franco's magic, e.g.: https://github.com/spezi77/android_kernel_google_msm/commit/c6df9d72c12d867b47cfb0714b4c6614e740f32e

Similar to using Grarak's Kernel Adiutor, when entering "Screen" menu, the app just crashes and results in a system reboot.

**Comment by JoeSchubert** [comment]
If you could provide the SYSFS paths, files, and expected values, that would be very helpful.

I assume they'll be /sys/module/gamma_control/parameters/ etc etc etc

But if you could provide the expected values, that would be super...

Also, the crash from logcat.

**Comment by spezi77** [comment]
Unfortunately there is nothing useful in the logcat about it: https://gist.github.com/spezi77/6dceef9830a4dd95ca16

P.S.: I will look into the SYSFS paths, files, and expected values at the weekend..

**Comment by spezi77** [comment]
I stumbled across the right pieces of information. ;)

1) Change RGB colors (values 0..255) and instantly apply them with the second command:
echo "255 255 255" > /sys/devices/platform/kcal_ctrl.0/kcal
echo 1 > /sys/devices/platform/kcal_ctrl.0/kcal_ctrl

2) GAMMA profile (Nexus 7 2013): 
echo "118" > /sys/class/misc/gammacontrol/blue_blacks
echo "118" > /sys/class/misc/gammacontrol/green_blacks
echo "118" > /sys/class/misc/gammacontrol/red_blacks
echo "114" > /sys/class/misc/gammacontrol/blue_greys
echo "114" > /sys/class/misc/gammacontrol/green_greys
echo "114" > /sys/class/misc/gammacontrol/red_greys
echo "21" > /sys/class/misc/gammacontrol/blue_mids
echo "21" > /sys/class/misc/gammacontrol/green_mids
echo "21" > /sys/class/misc/gammacontrol/red_mids
echo "48" > /sys/class/misc/gammacontrol/blue_whites
echo "48" > /sys/class/misc/gammacontrol/green_whites
echo "48" > /sys/class/misc/gammacontrol/red_whites
echo "2" > /sys/class/misc/gammacontrol/contrast
echo "0" > /sys/class/misc/gammacontrol/brightness
echo "80" > /sys/class/misc/gammacontrol/saturation

2) GAMMA profile (PA Halfbreed)
echo "118" > /sys/class/misc/gammacontrol/blue_blacks
echo "118" > /sys/class/misc/gammacontrol/green_blacks
echo "118" > /sys/class/misc/gammacontrol/red_blacks
echo "64" > /sys/class/misc/gammacontrol/blue_greys
echo "64" > /sys/class/misc/gammacontrol/green_greys
echo "64" > /sys/class/misc/gammacontrol/red_greys
echo "68" > /sys/class/misc/gammacontrol/blue_mids
echo "68" > /sys/class/misc/gammacontrol/green_mids
echo "68" > /sys/class/misc/gammacontrol/red_mids
echo "32" > /sys/class/misc/gammacontrol/blue_whites
echo "32" > /sys/class/misc/gammacontrol/green_whites
echo "32" > /sys/class/misc/gammacontrol/red_whites
echo "25" > /sys/class/misc/gammacontrol/contrast
echo "4" > /sys/class/misc/gammacontrol/brightness
echo "80" > /sys/class/misc/gammacontrol/saturation

Source: http://forum.xda-developers.com/nexus-4/general/nexus-4-color-settings-spreadsheet-t2039607/page137

These have been just two possible gamma profiles out of many (~100). A simple solution would be to allow the user to manually apply changes. In a second step it would be great, if the app would allow the user to load/save custom profiles. On xda people were sharing profiles and organizing them with help of spreadsheets.

BTW, a "screen profile" should consist of a RGB settings and a gamma profile.

Maybe the app could provide a list with the top ten screen profiles (of course the nice looking ones).

Sorry for my bad english, and I hope that you could understand all of that stuff.. it is a little late over here in Germany.. I should get some sleep now.. 

What are your thoughts?

**Comment by JoeSchubert** [comment]
If the app is crashing, there should have been a java crash just after your last line "03-17 22:38:06.328 19176 19176 I Kernel Adiutor: Opening ScreenFragment" if that's where it's crashing at. That crash is what I would need to see to do anything about that.

As for the profiles, I might be able to make it look for a gamma_profiles.json in the app's data directory before using the built-in profiles. That might take some time for me to figure out though.

The values that you posted _look_ like the same as gammacontrol. https://github.com/yoinx/kernel_adiutor/blob/5becfa80e8a4dae67d6c0ee94f8daae04136f9cd/app/src/main/assets/gamma_profiles.json#L123

I don't really see a reason why it _shouldn't_ work. It has the right path in the constants and there are profiles in that file (the previous link). 

I would really need to see something in the logcat to narrow it down beyond that, but the info isn't there.

**Comment by JoeSchubert** [comment]
Can you give this a try? 
https://github.com/yoinx/kernel_adiutor/commit/4dc128e9791e783c52d7684322c564cc62c78bb2

I'm just drawing at straws with that, I'm wondering if maybe that helps the issue.

**Comment by spezi77** [comment]
Yep, will test it. Thank you! ;)

**Comment by spezi77** [comment]
Tested it. But it didn't solve the one or the other problem.
https://gist.github.com/spezi77/870875533eafed8aca02

**Comment by JoeSchubert** [comment]
You're going to have to post a log from this app (or are you cherry picking them into the original kernel Adiutor?)

**Comment by spezi77** [comment]
I have forked your app and did a few mods for my custom rom. Furthermore I had to revert the package name to the original kernel Adiutor., in order to let the rom recognize the app and display it inside the rom settings (see https://github.com/spezi77/android_packages_apps_KernelAdiutor/commit/9ec7b4320a13489309c2bad7930ff3df0f03ad5a).

The logcat is from: https://github.com/spezi77/android_packages_apps_KernelAdiutor/tree/mod4n4

**Comment by JoeSchubert** [comment]
Ok.  Let's try to fix these one at a time.

I'm going to have to flash a kernel again that has the sound options...
Because that should have fixed it.

This gamma thing will be much more difficult since I don't have a device
that matches those controls.

**Comment by JoeSchubert** [comment]
To address the feature request: 
https://github.com/yoinx/kernel_adiutor/commit/6d899d232e948b0b7046f7998511e37ff34e4d6f

This allows placing files/gamma_profiles.json in the app's data directory. This is the best I can come up with for now to allow people to load their own profiles.

Now, I just need to figure out your crash. I can't find anything in the code that looks like it would be causing it though.

**Comment by spezi77** [comment]
Awesome, I am looking forward to trying it.

About the crash:
I have a suspicion now. The sysfs path (e.g. /sys/devices/platform/mipi_lgit.1537/kgamma_r) to the "regular" gamma interface is still present in my kernel with franco's gamma control, even though we don't use this interface.

Now, if I execute a command to print that sysfs gamma interface for a particular color (cat /sys/devices/platform/mipi_lgit.1537/kgamma_g), then a kernel panic can be observed and the device freezes in, followed by a restart.

Maybe that's exactly what happen when we enter the screen item in KA. Any idea how we can detect whether the kernel has franco's gamma control? Maybe check if /sys/class/misc/gammacontrol/ exists and in this case avoid reading from the "regular" gamma interface?

**Comment by JoeSchubert** [comment]
Thats sounds more like something that I was expecting :)

Yeah,  I'll see if it's not trying to read that value and make the
appropriate changes if it is.

**Comment by JoeSchubert** [comment]
Sorry for the crazy tab in on this...  I did it from my phone and didn't realize that the tiny tab in droidedit was actually a full tab. 
https://github.com/yoinx/kernel_adiutor/commit/26098a51c6bafe3a917fa4b075ec337ac0ef5aef

This should _really_ be fixed in the kernel driver to prevent the panic....  But this should hide it for now.

**Comment by spezi77** [comment]
Awesome, man. That has fixed it. Thanks a bunch!

**Comment by spezi77** [comment]
> This should really be fixed in the kernel driver 

I am open to suggestions where to look into.

**Comment by JoeSchubert** [comment]
Honestly, if the sysfs interfaces are causing a crash... you could likely
just remove/comment them.

https://github.com/spezi77/android_kernel_google_msm/blob/c6df9d72c12d867b47cfb0714b4c6614e740f32e/drivers/video/msm/mipi_lgit.c#L294

lines 294-498

**Comment by spezi77** [comment]
Thanks man, cleaned it up. Things just work fine. While looking into this, I have noticed that the sysfs interfaces belonged to a former commit with gamma control by faux123.

I should have better reverted that one prior to adding franco's commit.
