### ISSUE TITLE
Alternative HBM Sysfs node

### ISSUE THREAD

**Issue by JoeSchubert** [yoinx/kernel_adiutor#18]
_Note to myself. Sort of like a TODO list_

Apparently CM changed the sysfs node for HBM to: 

echo "1" > /sys/class/graphics/fb0/sre

Thanks to @NeoBuddy89 for pointing this out here: http://forum.xda-developers.com/showpost.php?p=66808574&postcount=4355

Remember to change line 502 to an array to support the multiple paths and screen.java to search them and store the value as a variable for use in the functions.

**Comment by neobuddy89** [comment]
Here is CM commit: https://github.com/CyanogenMod/android_kernel_moto_shamu/commit/86cdbc0ee5a5d4bc7dbf8f8021d2e17af4d50079

**Comment by JoeSchubert** [comment]
Thanks. I just wanted to add an issue so that when I get time after I get home next week I can make sure I get this stuff fixed.

**Comment by JoeSchubert** [comment]
Added support here: 
https://github.com/yoinx/kernel_adiutor/commit/59b611cb968e20ae6af6066b60e95c9cae57819e
