### ISSUE TITLE
Bricked thermal FC

### ISSUE THREAD

**Issue by ZdrowyGosciu** [yoinx/kernel_adiutor#25]
Hey 😃 I'm having FC when updating Bricked thermal config.. Value is saved, but app closes.

`06-01 06:45:59.480 V/sensors_hal_Light(1072): processReportInd: 350000 53.000000`
`06-01 06:45:59.480 D/sensors_hal_Ctx(1072): poll:polldata:1, sensor:1, type:5, x:53.000000 y:0.000000 z:0.000000`
`06-01 06:46:00.870 D/AndroidRuntime(11282): Shutting down VM`
`06-01 06:46:00.879 E/AndroidRuntime(11282): FATAL EXCEPTION: main`
`06-01 06:46:00.879 E/AndroidRuntime(11282): Process: com.grarak.kerneladiutor, PID: 11282`
`06-01 06:46:00.879 E/AndroidRuntime(11282): Theme: themes:{default=overlay:com.bulletproof136.material.ColorsDark, fontPkg:system, com.android.systemui=overlay:com.bulletproof136.material.ColorsDark, com.android.systemui.navbar=overlay:com.bulletproof136.material.ColorsDark}`
`06-01 06:46:00.879 E/AndroidRuntime(11282): java.lang.IllegalMonitorStateException: object not locked by thread before notify()`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at java.lang.Object.notifyAll(Native Method)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at com.grarak.kerneladiutor.fragments.kernel.ThermalFragment.onItemSelected(ThermalFragment.java:630)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at com.grarak.kerneladiutor.elements.cards.PopupCardView$DPopupCard$1.onItemSelected(PopupCardView.java:238)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at com.grarak.kerneladiutor.elements.cards.PopupCardView$1.onMenuItemClick(PopupCardView.java:70)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.support.v7.widget.PopupMenu.onMenuItemSelected(PopupMenu.java:227)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.support.v7.internal.view.menu.MenuBuilder.dispatchMenuItemSelected(MenuBuilder.java:811)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.support.v7.internal.view.menu.MenuItemImpl.invoke(MenuItemImpl.java:153)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:958)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.support.v7.internal.view.menu.MenuBuilder.performItemAction(MenuBuilder.java:948)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.support.v7.internal.view.menu.MenuPopupHelper.onItemClick(MenuPopupHelper.java:187)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.widget.AdapterView.performItemClick(AdapterView.java:310)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.widget.AbsListView.performItemClick(AbsListView.java:1195)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.widget.AbsListView$PerformClick.run(AbsListView.java:3235)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.widget.AbsListView$4.run(AbsListView.java:4080)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.os.Handler.handleCallback(Handler.java:739)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.os.Handler.dispatchMessage(Handler.java:95)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.os.Looper.loop(Looper.java:148)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at android.app.ActivityThread.main(ActivityThread.java:5475)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at java.lang.reflect.Method.invoke(Native Method)`
`06-01 06:46:00.879 E/AndroidRuntime(11282):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:726)`
`06-01 06:46:00.895 I/Kernel Adiutor(11282): Run command: echo 1574400 > /sys/kernel/msm_thermal/conf/allowed_low_freq`
`06-01 06:46:00.941 W/DropBoxManagerService(1072): Dropping: system_app_crash (1976 > 0 bytes)`
`06-01 06:46:00.952 W/ActivityManager(1072):   Force finishing activity com.grarak.kerneladiutor/.MainActivity`

**Comment by JoeSchubert** [comment]
It's from something that I had added back when I first started this and didn't know any better. Pretty sure it's fixed now. 
https://github.com/yoinx/kernel_adiutor/commit/fbd5bb0a2360358f9878e479107a2e6b8043871a

**Comment by ZdrowyGosciu** [comment]
Yes - dark/light = same results :) Thanks for the fix !!
