### ISSUE TITLE
VM hang

### ISSUE THREAD

**Issue by ZdrowyGosciu** [yoinx/kernel_adiutor#26]
Is it ROM bug? When I click "More" button in VM settings (e.g at the right of Min free Kilobytes) popup is displayed but app hangs and only force close helps..
Full log http://pastebin.com/6t0L4Jz9
Edit > Doesn't matter which theme I'm using..

**Comment by JoeSchubert** [comment]
I don't have this freeze at all with either of the "more"  buttons on that page. 

You sure you're not using a layer or cmte theme or something?

**Comment by ZdrowyGosciu** [comment]
You are right! It's CM Theme issue.. Thanks :+1:
