### ISSUE TITLE
Hotplugs

### ISSUE THREAD

**Issue by ghost** [yoinx/kernel_adiutor#28]
![screenshot_20160604-133049](https://cloud.githubusercontent.com/assets/18049475/15799321/18c4e270-2a59-11e6-83c9-8b9d65fa6a2d.png)
![screenshot_20160604-133102](https://cloud.githubusercontent.com/assets/18049475/15799322/18c57faa-2a59-11e6-8e1b-1e113d362b8f.png)
![screenshot_20160604-133119](https://cloud.githubusercontent.com/assets/18049475/15799320/18c3743a-2a59-11e6-9fba-5e15f6604eca.png)
![screenshot_20160604-132930](https://cloud.githubusercontent.com/assets/18049475/15799328/476dcbb4-2a59-11e6-9cb8-8320dbabd2e5.png)

[fix]Hotplugs: Show tunables for hotplugs without an enable/disable toggle.
I am a bit confused how hotplug settings work now with v11.
In v10 Intelliplug, AutoSMP and Bricked Hotplug had on/off toggles. I used Bricked Hotplug with my own settings. Now, in v11 i see the tunables for them without toggles, and a warning that more than 1 activated hotplug can cause problems.
Does it mean that Intelli,AutoSMP and Bricked are running at the same time now? Beacuse i can't disable Intelli and AutoSMP with a toggle. My CPU usage doesn't follow Bricked Hotplug settings. Last screenshot shows toggles in v10.

**Comment by JoeSchubert** [comment]
Yeah.  I need to revisit my logic for the hotplug section.  

I had reports that sometimes th tunables wouldn't show for hotplugs that didn't have a toggle...  So I tried to fix that,  in doing so it seems that I broke things.

**Comment by JoeSchubert** [comment]
@Bender80 , could you tell me what you have for values in:
/sys/module/autosmp/parameters/enabled
/sys/kernel/autosmp/conf/enabled

and 

/sys/kernel/msm_mpdecision/conf/enabled
/sys/kernel/bricked_hotplug/conf/enabled

and 
/sys/module/intelli_plug/parameters/intelli_plug_active
/sys/kernel/intelli_plug/intelli_plug_active

You'll onlly have one path out of each set.
That, or send me a sysfsdump from the settings menu in app.

**Comment by ghost** [comment]
This was created with test version posted some minutes ago.
https://www.dropbox.com/s/bsbcvaed3dtc7qg/sysfsdump.txt?dl=0

I can't find bricked_hotplug in sys/kernel
![screenshot_20160604-172715](https://cloud.githubusercontent.com/assets/18049475/15800440/e1c1a8dc-2a79-11e6-8bd4-27cf1a5059d9.png)

**Comment by ghost** [comment]
New test build works fine.

**Comment by JoeSchubert** [comment]
Works better.... Still not 100% yet though.

The hotplugs functions section is really a mess and needs a rewrite like I did with the fragment itself... Unfortunately I don't have time for that at the moment.... So I'm just trying to hack together some fixes.

**Comment by ghost** [comment]
At least i have toggles for all hotplugs now. If i encounter bad behavior, i will use the backup of v10.

**Comment by JoeSchubert** [comment]
No worries. 

I can tell you that the parameters for bricked won't work on the one I posted in my thread.... Though, I've already fixed that locally.

**Comment by ghost** [comment]
I don't know what you mean with "parameters for bricked won't work"
Values from bricked hotplug are saved in sys/kernel/msm_mpdecision
http://up.picr.de/25780077ka.jpg

**Comment by JoeSchubert** [comment]
Oh, I didn't figure they would. Hopefully they still do then with my local changes. 

You know you're welcome to catch me on hangouts instead of chatting through here: joseph.schubert@gmail.com

**Comment by ghost** [comment]
I don't use Hangouts. It's not very popular in Germany. Like G+. Everyone uses Whatsapp or Crapbook here.
*edit
Values for bricked still work with new test build

**Comment by JoeSchubert** [comment]
Sounds good, if everything's good then go ahead and close the issue.

**Comment by ghost** [comment]
And FYI, i deleted my xda account some weeks ago. It was getting worse and worse. Especially the Oneplus community was a pain in the ass. I decided that i have wasted too much time for the idiots. That's why i don't post in your thread or give thanks.

**Comment by JoeSchubert** [comment]
No worries man, I know that pain... It's a big part of the reason that I took a long hiatus from releasing any development work on XDA. They cater to people that are too lazy to even read before destroying their devices. But, from a site operator perspective, more people = more ad money. So, I get it.

But it chases too many competent people off the site because they just get fed up with it.
