### ISSUE TITLE
Feature request: add support for Stratosk dyn_hotplug

### ISSUE THREAD

**Issue by spezi77** [yoinx/kernel_adiutor#31]
Hey @yoinx 
It would be awesome if you could do me a favour and add a toggle and the settings for this hotplug.
Here is a commit with the required sysfs paths: https://github.com/robkingalex/kernel_msm/commit/d551008485640602789c6eb14558723a2d185aa3

Cheers ;)

**Comment by spezi77** [comment]
@yoinx: "why don't you just do it by yourself?"
spezi77: ya, why not?! Here you are: https://github.com/yoinx/kernel_adiutor/pull/32/commits/367d6256a13a148ac4e0d3835bc60f251e9af656

:D

**Comment by JoeSchubert** [comment]
Lol,  thanks.  I haven't had much time to add things lately...  Mostly just bug hunting.

**Comment by spezi77** [comment]
np. However, It is more efficient if you have the corresponding device and kernel nearby to test the results.
