### ISSUE TITLE
voltage table enhancement?

### ISSUE THREAD

**Issue by fizbanrapper** [yoinx/kernel_adiutor#34]
Any way to store the global voltage offset differently? If a user sets a +25 offset and doesn't remember what they set it to, they have no practical and easy way to know if they set it to +25 or +15 or anything else, for that matter.  Might require a lot of code re-writing.  Might be more effort than you want to put into it, but would be damned fine feature!

As always, amazing work @yoinx!

**Comment by RenderBroken** [comment]
I agree with this request. Would be nice for KAMod to somehow keep track.

**Comment by JoeSchubert** [comment]
I've actually already added this last night.  Currently the main catch is that it won't be able to get the values until the next reboot after installing the apk with the feature (or next reboot after clearing data). 

I've got more work to do on it,  but the concept is there in my commits (after the build I released yesterday)

**Comment by RenderBroken** [comment]
I am late to the party! lol. Thanks brother!

**Comment by JoeSchubert** [comment]
This feature should be present now as of these commits: 
https://github.com/yoinx/kernel_adiutor/commit/306dd03ebd4b616fed81415a34188de763c51db9
https://github.com/yoinx/kernel_adiutor/commit/624aeefc3f0951e5b7fa0e28950f271a0b85edf9
https://github.com/yoinx/kernel_adiutor/commit/dae3ca4cf1af76a55ea249dba4c9be92e6165cb3
