### ISSUE TITLE
Some bugs

### ISSUE THREAD

**Issue by fgl27** [yoinx/kernel_adiutor#42]
Hey yoinx.

I was using some of yours tree changes to update my KA. and found some things that don't work.

Android logging

It can't read the service state, if I disable or enable and go to misc is always on. I test this on yours V13...

I fix using mpdecision code for that... But only test on my tree.

https://github.com/bhb27/KernelAdiutor/commit/8c784cb34c99c82cad5bf88e8fdc6c800182cebf

After this two commit

https://github.com/yoinx/kernel_adiutor/commit/601d16118662e540029a9da9f17958aa18fed3bd

https://github.com/yoinx/kernel_adiutor/commit/ac3153b0e55459f199ac8b2f7c9df3b4f4dbfbf2

per app doesn't work it seems all ok but the profile don't load when open the app... I check the json and some app name are wrong.

I'm using CM base 6.0.1 ROM and have a lot of app freeze via Titanium backup, and some of the app on the json are the one I block, if I try to load the wrong app noting goes...  so some is wrong on those code. Maybe is only on my tree as I didn't try to build yours.

Reverting those two commit changes, all works for me, I don't understand those changes to Fix. :+1:

**Comment by shmuelr** [comment]
https://github.com/shmuelr/kernel_adiutor/commit/44fa08411065966e3e4989d2a2a7346c601e2326

That commit should fix this bug.
Please report if it works now for you.

Sorry for breaking this

**Comment by fgl27** [comment]
Thanks I do some test and let you know later.

I found one more minor on the profiles, is just a visual one...

When yoinx remove the plugins it break the function to display only kernel section on the section selection when add a new profile, this doesn't cause any problem is just visual.

the Fix
https://github.com/bhb27/KernelAdiutor/commit/c0dc7d93866ce5bf6f22c13599ca138ff998bcd5.

**Comment by fgl27** [comment]
https://github.com/shmuelr/kernel_adiutor/commit/44fa08411065966e3e4989d2a2a7346c601e2326

Works 100% :+1:

**Comment by shmuelr** [comment]
Gonna close this. Re-open if needed
