### ISSUE TITLE
CPU Voltage not working after this...

### ISSUE THREAD

**Issue by fgl27** [yoinx/kernel_adiutor#48]
@shmuelr 

check this commit 

https://github.com/yoinx/kernel_adiutor/commit/da98179919051fcf8835b3c0aec1fcaf9d892753

It makes the error toast do display, and the CPU_Voltage featuring stop work...

may be need to clean the app data then reboot to see it...
:+1:

**Comment by shmuelr** [comment]
Thanks!

Should be fixed here https://github.com/yoinx/kernel_adiutor/pull/49

Please report if this works now

**Comment by fgl27** [comment]
Works perfect.

with clean data, and after making changes reboot etc...

:+1:

**Comment by shmuelr** [comment]
Merged

**Comment by JoeSchubert** [comment]
No idea why I re-opened this....
