### ISSUE TITLE
Sound: FC upon changing the Headphone Gain (mako kernel with faux123 sound control)

### ISSUE THREAD

**Issue by spezi77** [yoinx/kernel_adiutor#5]
When I don't use the option "Independent Head Phone Gain" and then change the Headphone Gain, the app has a FC. See logcat: https://gist.github.com/spezi77/f561ce97741e4d43a2b1

The other options work fine. Also when using "Independent Head Phone Gain" I can change Headphone Gain Left/Right without any issue.

**Comment by JoeSchubert** [comment]
This should fix it. 
https://github.com/yoinx/kernel_adiutor/commit/921cc3c28e570e431f1ea8f7d1dd3f8848fb568b

I assume that you're building your own apk? If so, could you test it with that change and make sure that it works?

That was just something dumb on my part.

**Comment by spezi77** [comment]
Thanks very much. I will add your commit and test it by tomorrow with a new build. :)

**Comment by JoeSchubert** [comment]
https://github.com/yoinx/kernel_adiutor/commit/a7eed03b2012398860537d9d6dcb9b15d05e8b55

Tested this one on a different kernel, it fixes the issue.

**Comment by spezi77** [comment]
Thanks, that has fixed it.
