### ISSUE TITLE
CPU_Current

### ISSUE THREAD

**Issue by fgl27** [yoinx/kernel_adiutor#50]
Google has add the current for it frequency for it core I don't know maybe is possible to control these values like CPU_Voltage. It was add to 8084 devices and some other msm8**\* devices..

the commit that add it 8084
https://github.com/bhb27/BHB27Kernel/commit/0e332d0cf9abbeeb9d59f98e3942c235456fe5e7
+
https://github.com/bhb27/BHB27Kernel/commit/9d21c12b01217b6db0bfee64e7850e23ae120db4

The file is at:
sys/devices/system/cpu/cpufreq/current_in_state

the file content is:
https://github.com/bhb27/KernelAdiutor/blob/json/current_in_state

My have over and under frequency, the file content will be empty if the Dev has made over and/or under clock and didn't add the values for the new frequency on the current table so is need to do something like this:

https://github.com/bhb27/BHB27Kernel/commit/778d75b94084c481f39b433ede2d8bfc261a4c13

@yoinx @shmuelr if you guys can make KA to control this let me know.

**Comment by JoeSchubert** [comment]
All of these links are now going to 404's. 

Not sure if this is still a valid issue.

However, I haven't seen any kernels that actually have these current values as a tunable. So yes, they're there... however they are not modifiable from user-space.

**Comment by fgl27** [comment]
I know those repo are old I rename things...

the path is 444 but can be easily change
https://github.com/bhb27/BHB27Kernel/commit/0e332d0cf9abbeeb9d59f98e3942c235456fe5e7#diff-9441bc95586fefeea51df68d02f50e53R257

I had no time to go try change this files, by the way the file output is seems really hard to make KA change it, but I will try then I up here...

Fix the links of first post, just for future reference...

**Comment by JoeSchubert** [comment]
Do you have the contents of that sysfs node?

**Comment by fgl27** [comment]
current_in_state file? if not let me know...

the one from my device is

https://github.com/bhb27/KernelAdiutor/blob/json/current_in_state

**Comment by JoeSchubert** [comment]
Yeah,  but that looks to be something in your source...  Not what is actually being read from the sysfs node you referenced.  Or is it? 

Also.  What you're posting (and what google added)  is simple an estimated current draw poker freq for the cpu...  Which really,  isn't very useful since it's not coming from the regulators,  it's just calculating the time in state vs the current for that state listed in the dtsi.  

Their commits don't also for userspace control

**Comment by fgl27** [comment]
https://github.com/bhb27/KernelAdiutor/blob/json/current_in_state
this files above is from my device of path below
sys/devices/system/cpu/cpufreq/current_in_state

**Comment by JoeSchubert** [comment]
Yeah,  I don't think you're getting my point.  Those aren't modifiable values.  Can you change them by hand?

**Comment by fgl27** [comment]
I can set to 777 but can't change a number inside, no root app I have can save the file...

I understand what you are writing.

The thing is some thing don't make much sense to me (maybe because for my lack of experience with this), way have a value of current in micro ampere (for it freq of it core) exported if that is not intended for some kind of use. I grep for "current_in_state" doesn't have one single file on the devices that uses it in all of lib's and bin etc... of all Motorola devices from CM repo vendor folder or my local stock ROM of my device none give me a answer for the greep, and some of those devices have that commit in Motorola Repo, that file never change it state the number inside are always the same, I don really see a use for it, I thought it was just like the voltage table a output file that can be change and will limited max current. I know that those voltage table are not default they don't come from stock kernel but they have similarity...

The voltage table is other thing I don't get if I read the file what is on the file and what KA "echo" when it make a change are not the same, if I change by hand the device crash and reboot.

That is way I start this, just because I can't change it by hand does not mean that have no other way, the voltage table is one example...
