### ISSUE TITLE
Separate Apply on boot in cpu governor setting.

### ISSUE THREAD

**Issue by MF-Debug** [yoinx/kernel_adiutor#51]
A separate apply on boot toggle option will be very helpful as whenever i tune my governor, the settings don't stick after rebooting my device even if i have turned on apply on boot in cpu section.

**Comment by JoeSchubert** [comment]
@killoid which settings? Which governor?

I cant reproduce this, my governor settings are applying fine after a reboot.

**Comment by MF-Debug** [comment]
never mind. it was my fault. i was using yankactive governor. now it is working fine.
