### ISSUE TITLE
Hima Hotplug strings

### ISSUE THREAD

**Issue by yarpiin** [yoinx/kernel_adiutor#55]
if [ -d "/sys/kernel/hima_hotplug" ]; then
                $BB echo '{ SPane:{
                    title:"Hima Hotplug"
                }},'
                if [ -f "/sys/kernel/hima_hotplug/hima_hotplug_active" ]; then
                    HIMAN=`$BB cat /sys/kernel/hima_hotplug/hima_hotplug_active`
                    $BB echo '{ SCheckBox:{
                        label:"Hotplug Enabled",
                        description:"Hotplug Driver ported from HTC m9.",
                        default:'$HIMAN',
                        action:"generic /sys/kernel/hima_hotplug/hima_hotplug_active"
                }},'
                fi
                if [ -f "/sys/kernel/hima_hotplug/current_profile_no" ]; then
                    HP=`$BB cat /sys/kernel/hima_hotplug/current_profile_no`;
                    $BB echo '{ SOptionList:{
                        title:"Hotplug Style",
                        description:"Sets how hotplug drives cpus.",
                        default:'$HP',
                        action:"generic /sys/kernel/hima_hotplug/current_profile_no",
                        values:{
                            1:"Power Save", 0:"Balanced", 2:"Performance"
                        }
                }},'
                fi
                if [ -f "/sys/kernel/hima_hotplug/min_cpus_online" ]; then
                    CPU=`$BB cat /sys/kernel/hima_hotplug/min_cpus_online`
                    $BB echo '{ SSeekBar:{
                        title:"Minimum CPUs online at anytime",
                        min:1,
                        max:8,
                        step:1,
                        default:'$CPU',
                        action:"generic /sys/kernel/hima_hotplug/min_cpus_online"
                    }},'
                fi
                if [ -f "/sys/kernel/hima_hotplug/max_cpus_online" ]; then
                    CPU=`$BB cat /sys/kernel/hima_hotplug/max_cpus_online`
                    $BB echo '{ SSeekBar:{
                        title:"Maximum CPUs online at anytime",
                        min:1,
                        max:8,
                        step:1,
                        default:'$CPU',
                        action:"generic /sys/kernel/hima_hotplug/max_cpus_online"
                    }},'
                fi
                if [ -f "/sys/kernel/hima_hotplug/def_sampling_ms" ]; then
                DS=`$BB cat /sys/kernel/hima_hotplug/def_sampling_ms`;
                    $BB echo '{ SSeekBar:{
                        title:"Defer Sampling",
                        min:0,
                        max:100,
                        unit:" ms",
                        step:1,
                        default:'$DS',
                        action:"generic /sys/kernel/hima_hotplug/def_sampling_ms"
                    }},'
                fi
            fi`

**Comment by yarpiin** [comment]
This is mine settings from UKM if possible please add it into KA

**Comment by JoeSchubert** [comment]
@yarpiin can you give this build a test?

https://www.androidfilehost.com/?fid=24588232905722036

**Comment by yarpiin** [comment]
Works ok !! Great job :)

**Comment by JoeSchubert** [comment]
Taken care of here: 
https://github.com/yoinx/kernel_adiutor/pull/57
