### ISSUE TITLE
List of CPU governors broken

### ISSUE THREAD

**Issue by spezi77** [yoinx/kernel_adiutor#6]
Hey man,
Sorry to bother you again. ;)
I have now added a bunch of governors into my kernel, so that in the end there are 32 governors.

When I use your app to change the governor, then in the list I see the first 17 governors normal. But item no. 18 is combined with the next one, e.g. interactive_proelementalx.

First I thought that I messed up something. I looked into my kernel config, but I couldn't figure any issue there.

Any idea what went wrong here?

**Comment by JoeSchubert** [comment]
So,  the names are combining on one list item? 

Can you tell me how they show up in /sys/devices/system/cpu/cpuX/cpufreq/scaling_available_governors

They should all be listed separated by spaces.

**Comment by spezi77** [comment]
root@:/ # cat sys/devices/system/cpu/cpu0/cpufreq/scaling_available_governors  
zzmoove xperience wheatley tripndroid smartmax_eps smartmax smartassV2 smartassH3 preservative pegasusq ondemandplus ondemand_eps nightmare lulzactive intellimm intellidemand intelliactive interactive_proelementalx dyninteractive darkness dancedance alucard abyssplugv2 interactive conservative ondemand powersave wave lionheart bioshock performance

**Comment by spezi77** [comment]
Here we have the culprit. The space is missing between interactive_pro and elementalx. How could this happen?

**Comment by JoeSchubert** [comment]
Dunno.  But the app is doing exactly what is supposed to.  You have something wrong in your kernel causing that.

**Comment by spezi77** [comment]
You were right, after I have deleted INTERACTIVE_PRO gov, this weird issue was gone.
Thanks for your hint.. highly appreciated!
