### ISSUE TITLE
Adreno_Idler reverts to "disabled" in KA Mod GUI

### ISSUE THREAD

**Issue by Nachtfalkeaw** [yoinx/kernel_adiutor#61]
I am running Ressurrection Remix 5.7.2 (Adnroid 6.0.1) and Sensei Kernel 2.3R3 on Xiaomi Mi 4i.
Kernel Aditor Mod V15.

In the GPU menue I set "Adreno_Idler" to enable, it adds the command to the startup command but every time leaving the "GPU" menue and then go back to "GPU" menue shows that Adreno_Idler again disabled .

**Comment by JoeSchubert** [comment]
This should be fixed by 
https://github.com/yoinx/kernel_adiutor/commit/d9396b387c0fc41f3d1ba655a41fa26d8dc6accd
