### ISSUE TITLE
GPU max frequency reverts after reboot

### ISSUE THREAD

**Issue by Nachtfalkeaw** [yoinx/kernel_adiutor#63]
I am running Ressurrection Remix 5.7.2 (Adnroid 6.0.1) and Sensei Kernel 2.3R3 on Xiaomi Mi 4i.
Kernel Aditor Mod V15.

I am setting the max frequency of the GPU to 465MHz instead of 700MHz. This command is in the "startup commands" and is persistent until reboot. After a reboot it changes back to 700MHz.

Going to the KA Mod settings --> Apply on boot --> Test will set the correct value in "GPU" for maximum frequency.

Delay is set to 20sec after reboot.

**Comment by JoeSchubert** [comment]
If the Test function works... this is a conflict outside of the app. Your kernel is likely locking the value somewhere for a certain amount of time.

The test function operates exactly the same as the apply on boot does when receiving the boot complete intent
