### ISSUE TITLE
Do not disable/enable CPU on startup commands when changing something on "CPU"

### ISSUE THREAD

**Issue by Nachtfalkeaw** [yoinx/kernel_adiutor#67]
I am running Ressurrection Remix 5.7.2 (Adnroid 6.0.1) and Sensei Kernel 2.3R3 on Xiaomi Mi 4i.
Kernel Aditor Mod V15.

I noticed that KA Mod will add some startup commands regarding the current CPU state.
So if I go to "CPU" menue and changing frequencies and so on then it is common that the CPU cores will turn on and of automatically without doing anything. When leaving this menue and I only changed the minimum or maximum CPU MHz then KA Mod will add the commands to disable/enable CPU cores to the startup commands.

In most cases this shouldn't be a problem because the CPU hotplug dynamically enables/disables cores but I think this should not be in startup commands if the user did not change anything on CPU cores actively.

So the CPU menue should have the possibility like "CPU core selection" = manually oder dynamic.
When set to manually the cores should be configured by the user and the commands should go to the startup commands.

If set to dynamically it should be ignored for startup commands.

Perhaps this feature could be combined with the option "Max CPUs Online" so that the user can select which of the CPUs should be online. So I have 4 "big" cores and 4 "little" cores. If I set it to 6 cores maximum I perhaps would like to use 4 "little" cores and only 2 "big" cores.

Same perhaps for "Minimum Cores allowed when screen off". Could be like the "MSM Limiter" where you can select "per core control".

**Comment by JoeSchubert** [comment]
The reason that it does this is because the CPUs have to be active for changes to be made to them. 

This unfortunately cannot be changed.
