### ISSUE TITLE
Showing the actual charging rate in KA Mod --> "Power and Battery" 

### ISSUE THREAD

**Issue by Nachtfalkeaw** [yoinx/kernel_adiutor#68]
I am running Ressurrection Remix 5.7.2 (Adnroid 6.0.1) and Sensei Kernel 2.3R3 on Xiaomi Mi 4i.
Kernel Aditor Mod V15.

Would be nice to see the actual charing rate in "Power and Battery".

On my phone these values seem to be somewhere here:
/sys/class/power_supply/

But unfortunately I could not locate the exact file until now. Perhaps you can find it.

**Comment by fgl27** [comment]
![screenshot_20160809-212209](https://cloud.githubusercontent.com/assets/13755892/17538041/2c13bf88-5e78-11e6-8f67-2fa67fc0c695.png)

I did that on the Mod version I use for my kernel you can use as example and do it

https://github.com/bhb27/KA27/commit/d4a28c5e40dd0d6b1e8f6401579ad1ada0aef421
https://github.com/bhb27/KA27/commit/37149f19c13504ae4da92f1ec9e6ed07f1f8782d
https://github.com/bhb27/KA27/commit/96905322d704e123f11e29ce9c115baccb3ad7a6

The path is not "universal" on the first commit on the below commit I fix that
https://github.com/bhb27/KA27/commit/6ff047d02dea45d5524795cb8aeb4a74d99e5296

**Comment by fgl27** [comment]
@Nachtfalkeaw
my app is only 100% for my kernel but you can try to see if that featuring works in yours device
then you can confirm here that the path and commits are OK.

[Download](https://www.androidfilehost.com/?w=files&flid=48767) 

:+1:

**Comment by Nachtfalkeaw** [comment]
Hi,

unfortunately I could not find any file which contains the charging speed in these folders. Further your app does not show it.
It shows everything but not "Battery charging/discharging" and not "Battery charging mode".

For curiosity I can see tha charging rate of 1500mAh on my lockscreen ....

**Comment by JoeSchubert** [comment]
Yeah,  I really don't care about this.  There are plenty of apps that do this already and it's not a kernel control feature.
