### ISSUE TITLE
Some settings don't stick when default profile is activated and some profiles has issues with  staying on 

### ISSUE THREAD

**Issue by Madmaxx636** [yoinx/kernel_adiutor#77]
The main issues I've been having are with the default profile not enabling everything when it is automatically triggered to apply. Like GPU max freq doesn't set to the profile's settings and sometimes other things. Another issue is with the per app profiles not enabling or staying enabled when using said app
Example: I open YouTube. It enables the profile that is set to apply when that app is open. Sometimes it will flip between the home/default profile and the profile that is applied to the YouTube app. This doesn't happen with just the YouTube app. It sometimes happens with many other apps too.

**Comment by JoeSchubert** [comment]
The profiles only save settings that have been toggled/changed in app. 

They won't restore your kernel's default settings... I would have to scan and save all of those on boot in order to do that.
