### ISSUE TITLE
Values for Sultan's CPU Input Boost driver

### ISSUE THREAD

**Issue by EyeCantCU** [yoinx/kernel_adiutor#85]
Hi! 

I had noticed that you had said that you would add features were we able to provide the sysfs paths for things and what their intention is. Sultan's CPU input boost driver is better than CAFs implementation in my experience and it would be awesome were you to add native support for it in your app

Here are the values:

/sys/kernel/cpu_input_boost/enabled (export 1 to enable the driver, 0 to disable it)
/sys/kernel/cpu_input_boost/ib_freqs (you choose two frequencies, one acts as the initial boosting frequency and the other is used later so for instance on an msm8974pro device, Sultan has it set to 1190400 and 1497600)
/sys/kernel/cpu_input_boost/ib_duration_ms (you choose the input boost duration in milliseconds)

That is all.

Just a suggestion, but maybe in the future we could manage sysfs stuffs from KA just like in EX kernel manager? Then there wouldn't have to be so many feature requests... Though native support is good

**Comment by JoeSchubert** [comment]
Do you happen to know the min/max values for /sys/kernel/cpu_input_boost/ib_duration_ms  ?

**Comment by EyeCantCU** [comment]
3000 appears to be the max, and 0 is the min. It increases by intervals of 100. Any more information you need by chance?

**Comment by JoeSchubert** [comment]
No, that should be it. Thanks. I'll try to add it in here shortly.

**Comment by EyeCantCU** [comment]
Awesome! Thanks for giving it a look
