### ISSUE TITLE
Schedule workqueues on awake CPUs to save power

### ISSUE THREAD

**Issue by nico151999** [yoinx/kernel_adiutor#88]
Hi,

I'm using your Kernel Adiutor mod on my Beanstalk builds (experimental branch). I just compiled your sources using gradle. First I want to thank you for providing this awesome project but I also want to tell you about a bug I experience. Dunno if it's a Snapdragon 820/821 related bug but if I enable "Schedule workqueues on awake CPUs to save power" in the CPU section this setting is disabled whenever I reopen this activity so I assume it is not applied on my Snapdragon 820 HTC 10 phone. If I use the official Kernel Adiutor by Grarak this feature can be applied. The catlog doesn't tell me anything helpful and due to a lack of Java skills I couldn't fix this by myself to send a pull request. I hope you're willing to help me and persumeably many others as well. Thanks a lot in advance.

Regards
Nico

**Comment by EyeCantCU** [comment]
You need to compile your kernel with CONFIG_WQ_POWER_EFFICIENT_DEFAULT enabled. If you've picked the commits for power efficient workqueues but never enabled them then it won't work as then you are scheduling everything on the CPU by default instead of the scheduler

**Comment by nico151999** [comment]
Okay, that seems to be a solution thanks!
